name: Update Patch Zip Files

on:
  workflow_dispatch:
  # pull_request:
  #  types: [closed]

jobs:
  patch:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, '[ZIP PATCHES]'))
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Update patches repo wide
        run: |
          python3 scripts/patch_zip.py ./

      - name: Commit and push patch files
        run: |
          echo "â³ Waiting 2 minutes before uploading..."
          sleep 120
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hacks/*/patches.zip || true

          if ! git diff --cached --quiet; then
            git commit -m "[PATCH REZIP] Update Patch Files"
            git push origin master
          else
            echo "No changes to commit."
          fi

  none:
    if: >
      github.event_name == 'pull_request' &&
      (github.event.pull_request.merged != true ||
      !startsWith(github.event.pull_request.title, '[ZIP PATCHES]'))
    runs-on: ubuntu-latest
    steps:
      - name: Skip message
        run: echo "No [ZIP PATCHES] PR merged. Skipping."
